const base=new URL('./',import.meta.url),storageKey='spiral.private:'+base.pathname;
const status=document.querySelector('#status'),form=document.querySelector('#unlock'),modes=document.querySelector('#modes');
const bytes=s=>Uint8Array.from(atob(s),c=>c.charCodeAt(0)),b64=a=>btoa(String.fromCharCode(...new Uint8Array(a)));
async function rpc(message){await navigator.serviceWorker.ready;const worker=navigator.serviceWorker.controller;if(!worker)throw Error('The presentation is still preparing. Please try again.');return new Promise((resolve,reject)=>{const channel=new MessageChannel();const timeout=setTimeout(()=>reject(Error('Could not prepare presentation. Please refresh.')),30000);channel.port1.onmessage=({data})=>{clearTimeout(timeout);data.ok?resolve(data):reject(Error(data.error||'Could not unlock.'));};worker.postMessage(message,[channel.port2]);});}
async function start(){if(!('serviceWorker'in navigator)||!crypto.subtle)throw Error('Please use an up-to-date Chrome, Edge, Safari, or Firefox browser.');await navigator.serviceWorker.register(new URL('sw.js',base),{scope:base.pathname,updateViaCache:'none'});await navigator.serviceWorker.ready;if(!navigator.serviceWorker.controller)await new Promise(resolve=>navigator.serviceWorker.addEventListener('controllerchange',resolve,{once:true}));}
const ready=start();
async function unlock(password,saved){await ready;const metadata=await(await fetch(new URL('access.json',base),{cache:'no-store'})).json();let raw;
 if(saved?.revision===metadata.revision)raw=bytes(saved.key);else{if(!password)throw Error('Enter the password to open the presentation.');const material=await crypto.subtle.importKey('raw',new TextEncoder().encode(password),'PBKDF2',false,['deriveBits']);raw=await crypto.subtle.deriveBits({name:'PBKDF2',hash:'SHA-256',salt:bytes(metadata.salt),iterations:metadata.iterations},material,256);}
 const key=await crypto.subtle.importKey('raw',raw,'AES-GCM',false,['decrypt']);const response=await fetch(new URL(metadata.index,base));if(!response.ok)throw Error('The presentation could not be downloaded. Please try again.');
 let manifest;try{const packed=await crypto.subtle.decrypt({name:'AES-GCM',iv:bytes(metadata.iv)},key,await response.arrayBuffer());manifest=await new Response(new Blob([packed]).stream().pipeThrough(new DecompressionStream('gzip'))).json();}catch{throw Error('That password did not unlock the presentation.');}
 if(manifest.version!==1||!manifest.entries?.['index.html'])throw Error('Invalid presentation package.');
 const session={revision:metadata.revision,key:b64(raw),manifest};sessionStorage.setItem(storageKey,JSON.stringify(session));await rpc({type:'unlock',key,manifest,revision:metadata.revision});form.hidden=true;modes.hidden=false;status.textContent='';document.querySelector('#password').value='';
 const target=new URLSearchParams(location.search).get('return');if(target){const dest=new URL(target,base);if(dest.origin===base.origin&&dest.pathname.startsWith(base.pathname+'app/')){if(!dest.hash&&location.hash)dest.hash=location.hash;location.replace(dest.href);}}
}
form.addEventListener('submit',async e=>{e.preventDefault();const button=form.querySelector('button');button.disabled=true;status.textContent='Unlocking…';try{await unlock(document.querySelector('#password').value);}catch(e){status.textContent=e.message;}finally{button.disabled=false;}});
document.querySelector('#lock').onclick=async()=>{sessionStorage.removeItem(storageKey);await rpc({type:'lock'});modes.hidden=true;form.hidden=false;status.textContent='Presentation locked.';};
try{const saved=JSON.parse(sessionStorage.getItem(storageKey)||'null');if(saved){status.textContent='Opening presentation…';await unlock('',saved);}else await ready;}catch(e){sessionStorage.removeItem(storageKey);status.textContent=e.message;}
